--- #YAML:1.0
name: AudioFile-Info-MP3-ID3Lib
version: 1.03
author:
  - Dave Cross, E<lt>dave@dave.org.ukE<gt>
abstract: Perl extension to get info from MP3 files.
license: perl
requires:
  AudioFile::Info: 0
  MP3::ID3Lib: 0
  perl: 5.6.0
build_requires:
  Module::Build: 0
dynamic_config: 1
provides:
  AudioFile::Info::Build:
    file: lib/AudioFile/Info/Build.pm
  AudioFile::Info::MP3::ID3Lib:
    file: lib/AudioFile/Info/MP3/ID3Lib.pm
    version: 1.03
generated_by: Module::Build version 0.25
